name: Test PoshJohn Module

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[github.ref == 'refs/heads/main'] }}

jobs:

  build-john:
    name: Build John Binaries (${{ matrix.osname }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - osname: Windows
            os: windows-latest
            build_script: /scripts/build-john-windows.ps1
            john_out: /john/windows/run
          - osname: Linux
            os: ubuntu-latest
            build_script: /scripts/build-john-linux.sh
            john_out: /john/linux/run
          - osname: MacOS
            os: macos-latest
            build_script: /scripts/build-john-macos.sh
            john_out: /john/macos/run
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build John the Ripper (Windows)
        if: matrix.osname == 'Windows'
        shell: pwsh
        run: ${{github.workspace}}${{ matrix.build_script }}

      - name: Build John the Ripper (Linux/MacOS)
        if: matrix.osname != 'Windows'
        shell: bash
        run: |
          scriptPath=${{github.workspace}}${{ matrix.build_script }}
          chmod +x $scriptPath
          if [ "${{ matrix.osname }}" = "Linux" ]; then
            sudo $scriptPath
          else
            $scriptPath
          fi

      - name: Upload John Binaries
        uses: actions/upload-artifact@v4
        with:
          name: john-${{ matrix.osname }}
          path: ${{ github.workspace }}${{ matrix.john_out }}
          if-no-files-found: error

  build-module:
    name: Build PowerShell Module
    needs:
      - build-john
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Repo checkout

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download John Binaries (Windows)
        uses: actions/download-artifact@v4
        with:
          name: john-Windows
          path: ${{ github.workspace }}/john/windows/run

      - name: Download John Binaries (Linux)
        uses: actions/download-artifact@v4
        with:
          name: john-Linux
          path: ${{ github.workspace }}/john/linux/run

      - name: Download John Binaries (MacOS)
        uses: actions/download-artifact@v4
        with:
          name: john-MacOS
          path: ${{ github.workspace }}/john/macos/run

      - name: Build and test module
        shell: pwsh
        run: ./PowerShellBuildTools/build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build

      - name: Capture PowerShell Module
        uses: actions/upload-artifact@v4
        with:
          name: PSModule
          path: out/*.nupkg
          if-no-files-found: error

  test:
    name: Test PowerShell Module (${{ matrix.info.name }})
    needs:
      - build-module
    runs-on: ${{ matrix.info.os }}
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        info:
        - name: Windows
          os: windows-latest
        - name: Linux
          os: ubuntu-latest
        - name: MacOS
          os: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore Built PowerShell Module
        uses: actions/download-artifact@v4
        with:
          name: PSModule
          path: out

      - name: Install Built PowerShell Module
        shell: pwsh
        run: |
          Import-Module ./PowerShellBuildTools/tools/helper.psm1 -Force
          Expand-Nupkg -ModuleManfifestPath ./src/PoshJohn.psd1 -OutputPath out

      - name: Run Tests - PowerShell
        shell: pwsh
        run: |
          ./PowerShellBuildTools/build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (${{ matrix.info.name }})
          path: ./out/TestResults/Pester.xml
          if-no-files-found: error

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'ubuntu-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'macos-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'windows-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml
